<script setup lang="ts">
import { computed, markRaw, nextTick, ref, shallowRef } from 'vue'
import { DataClientProvider, DevToolsOverlay, ThemeProvider, WorkspaceHost, captureWorkspace, createDataClient, createDataKey, createLocalStorageWorkspaceCollectionStorage, createLocalStorageWorkspaceLayoutStorage, createMockDataProvider, createSplitPane, createStackPane, createTabPane, createWidgetNavigator, createWidgetPane, createWindowGroupManager, createWorkspaceCollection, createWorkspaceEditController, createWorkspaceHistory, createWorkspaceLayoutManager, forgeDarkTheme, forgeLightTheme, provideWidgetNavigation, restoreWorkspace, serializeWorkspace, type WidgetForgeTheme, type WindowGroupSnapshot, type WorkspaceEditSnapshot, type WorkspaceRuntime } from 'widgetforge'
import { provideDemoControls, type DemoThemeName } from './demo-controls'
import { economyKey, registerEconomyResources } from './economic-domain'
import { playgroundWidgetRegistry } from './playground-widgets'
interface DemoMetric{label:string;value:number;unit:string}
const WORKSPACE_STORAGE_KEY='widgetforge.playground.fullscreen.v3',THEME_STORAGE_KEY='widgetforge.playground.theme',EDIT_STORAGE_KEY='widgetforge.playground.edit.v1',GROUP_STORAGE_KEY='widgetforge.playground.groups.v1',LAYOUT_STORAGE_KEY='widgetforge.playground.layouts.v1',COLLECTION_STORAGE_KEY='widgetforge.playground.workspaces.v1'
function storedTheme():DemoThemeName{try{return window.localStorage.getItem(THEME_STORAGE_KEY)==='forge-light'?'forge-light':'forge-dark'}catch{return'forge-dark'}}
const themeName=ref<DemoThemeName>(storedTheme()),developerMode=ref(false),feedOnline=ref(true),themes:Record<DemoThemeName,WidgetForgeTheme>={'forge-dark':forgeDarkTheme,'forge-light':forgeLightTheme},activeTheme=computed(()=>themes[themeName.value])
const mockProvider=markRaw(createMockDataProvider()),gridPowerKey=createDataKey<DemoMetric>('demo.metric','grid-power'),warehouseKey=createDataKey<DemoMetric>('demo.metric','warehouse-stock')
mockProvider.register({key:gridPowerKey,initial:{label:'Grid Power',value:118.0,unit:'MW'},intervalMs:1_200,update:(current)=>({...current,value:current.value+0.5})});mockProvider.register({key:warehouseKey,initial:{label:'Warehouse Stock',value:640,unit:'t'},intervalMs:1_800,update:(current,tick)=>({...current,value:current.value+(tick%2===0?4:-2)})});registerEconomyResources(mockProvider)
const dataClient=markRaw(createDataClient(mockProvider,{cacheTimeMs:5_000}))
function createDemoWorkspaceCollection(){const create=(persist:boolean)=>createWorkspaceCollection({registry:playgroundWidgetRegistry,...(persist?{storage:createLocalStorageWorkspaceCollectionStorage(window.localStorage,COLLECTION_STORAGE_KEY)}:{})});try{return create(true)}catch{try{window.localStorage.removeItem(COLLECTION_STORAGE_KEY);return create(true)}catch{return create(false)}}}
const workspaces=markRaw(createDemoWorkspaceCollection()),restoredWorkspaceCollection=workspaces.list().length>0
const commandWorkspace=workspaces.list().find((workspace)=>workspace.id==='command')??workspaces.createWorkspace({id:'command',name:'Command',activate:true})
const windows=markRaw(commandWorkspace.windows),docks=markRaw(commandWorkspace.docks),navigator=markRaw(createWidgetNavigator(playgroundWidgetRegistry,windows)),edit=markRaw(createWorkspaceEditController())
provideWidgetNavigation(navigator)
function persistWorkspace():void{try{window.localStorage.setItem(WORKSPACE_STORAGE_KEY,serializeWorkspace(windows,docks))}catch{/* best effort */}}
function persistEdit():void{try{window.localStorage.setItem(EDIT_STORAGE_KEY,JSON.stringify(edit.snapshot()))}catch{/* best effort */}}
function restoreEdit():void{try{const stored=window.localStorage.getItem(EDIT_STORAGE_KEY);if(stored)edit.restore(JSON.parse(stored) as WorkspaceEditSnapshot)}catch{/* invalid storage falls back */}}
function openReferenceLayout():void{
  docks.add({id:'workspace-top',position:'top',thickness:58,minThickness:50,maxThickness:86,resizable:true,pane:createSplitPane({id:'workspace-top-root',axis:'horizontal',weights:[1,1],settings:{resizable:true,background:'surface'},children:[createWidgetPane({id:'workspace-nav-pane',widgetId:'demo.workspace-topbar',instanceId:'workspace-nav-widget',settings:{sizeMode:'fixed',size:620,minSize:520,maxSize:680,background:'surface'}}),createWidgetPane({id:'workspace-top-metric-pane',widgetId:'demo.live-metric',instanceId:'workspace-top-metric-widget',parameters:{resourceId:'grid-power'},settings:{sizeMode:'flex',minSize:180,background:'surface-raised'}})]})})
  docks.add({id:'workspace-bottom',position:'bottom',thickness:54,minThickness:48,maxThickness:88,resizable:true,pane:createWidgetPane({id:'workspace-command-pane',widgetId:'demo.workspace-commandbar',instanceId:'workspace-command-widget',settings:{background:'surface'}})})
  windows.open({widgetId:'market.ticker',instanceId:'market-main',title:'Helios Commodity Exchange',parameters:{commodity:'METALS',rows:14},position:{x:20,y:20},size:{width:620,height:430}});windows.snapWindow('market-main','left',{width:1200,height:720})
  windows.open({widgetId:'planet.summary',instanceId:'colony-main',title:'ARC-01 Colony Administration',parameters:{planetId:'ARC-01',compact:false},position:{x:640,y:32},size:{width:440,height:340}});windows.open({widgetId:'demo.alerts',instanceId:'alerts-main',position:{x:720,y:390},size:{width:430,height:300}});windows.open({widgetId:'demo.live-metric',instanceId:'telemetry-power',title:'Grid Telemetry',parameters:{resourceId:'grid-power'},position:{x:890,y:210},size:{width:250,height:155}})
  windows.openPane({instanceId:'operations-main',title:'Operations Matrix · fixed/flex/stack',position:{x:470,y:400},size:{width:590,height:270},minSize:{width:420,height:220},pane:createSplitPane({id:'operations-root',axis:'horizontal',weights:[1,1],children:[createWidgetPane({id:'operations-colony',widgetId:'planet.summary',instanceId:'operations-colony-widget',parameters:{planetId:'ARC-02',compact:true},settings:{sizeMode:'fixed',size:260,minSize:230,maxSize:300,background:'surface'}}),createStackPane({id:'operations-stack',settings:{sizeMode:'flex',background:'surface-raised'},children:[createTabPane({id:'operations-metrics',activeId:'operations-power',children:[createWidgetPane({id:'operations-power',widgetId:'demo.live-metric',instanceId:'operations-power-widget',parameters:{resourceId:'grid-power'},settings:{minSize:90,background:'surface-raised'}}),createWidgetPane({id:'operations-stock',widgetId:'demo.live-metric',instanceId:'operations-stock-widget',parameters:{resourceId:'warehouse-stock'},settings:{minSize:90,background:'canvas'}})]})]})]})})
  windows.openPane({instanceId:'economy-flow',title:'Colony Economy · Production → Inventory → Orders',position:{x:560,y:90},size:{width:640,height:360},minSize:{width:500,height:280},pane:createSplitPane({id:'economy-flow-root',axis:'horizontal',weights:[1,1],children:[createWidgetPane({id:'economy-production-pane',widgetId:'economy.production',instanceId:'economy-production-widget',settings:{minSize:220,background:'canvas'}}),createTabPane({id:'economy-flow-tabs',activeId:'economy-inventory-pane',children:[createWidgetPane({id:'economy-inventory-pane',widgetId:'economy.inventory',instanceId:'economy-inventory-widget',settings:{minSize:220,background:'canvas'}}),createWidgetPane({id:'economy-orders-pane',widgetId:'economy.orders',instanceId:'economy-orders-widget',settings:{minSize:220,background:'canvas'}})]})]})})
}
function clearWorkspace():void{for(const window of[...windows.list()])windows.close(window.instanceId,'api');for(const dock of[...docks.list()])docks.remove(dock.id)}
let restoredPersistedWorkspace=restoredWorkspaceCollection
function restoreReferenceLayout():void{if(restoredWorkspaceCollection)return;let stored:string|null=null;try{stored=window.localStorage.getItem(WORKSPACE_STORAGE_KEY)}catch{/* unavailable */}const restored=stored?restoreWorkspace(windows,stored,docks):null;if(restored?.valid&&restored.issues.length===0&&restored.restoredDocks.length>0){restoredPersistedWorkspace=true;return}clearWorkspace();openReferenceLayout()}
restoreReferenceLayout();restoreEdit()
function createDemoLayoutManager(){const create=(persist:boolean)=>createWorkspaceLayoutManager({registry:playgroundWidgetRegistry,windows,docks,...(persist?{storage:createLocalStorageWorkspaceLayoutStorage(window.localStorage,LAYOUT_STORAGE_KEY)}:{})});try{return create(true)}catch{try{window.localStorage.removeItem(LAYOUT_STORAGE_KEY);return create(true)}catch{return create(false)}}}
const layouts=markRaw(createDemoLayoutManager())
function hasLayout(name:string):boolean{return layouts.listLayouts().some((layout)=>layout.name===name)}
function buildReferencePreset(name:'Default'|'Trading'|'Operations'):void{clearWorkspace();openReferenceLayout();if(name==='Trading'){for(const id of['colony-main','alerts-main','operations-main'])windows.close(id,'api')}else if(name==='Operations')windows.close('market-main','api');layouts.saveLayout(name,{setDefault:name==='Default'})}
function seedDemoLayouts():void{const startup=serializeWorkspace(windows,docks),missing=(['Default','Trading','Operations'] as const).filter((name)=>!hasLayout(name));for(const name of missing)buildReferencePreset(name);if(!layouts.getDefaultLayout()&&hasLayout('Default'))layouts.setDefaultLayout('Default');if(missing.length>0){clearWorkspace();const restored=restoreWorkspace(windows,startup,docks);if(!restored.valid||restored.issues.length>0){clearWorkspace();openReferenceLayout();restoredPersistedWorkspace=false}}}
seedDemoLayouts()
function presetSnapshot(name:string){const preset=layouts.listLayouts().find((layout)=>layout.name===name);if(!preset)throw new Error(`missing demo layout ${name}`);return preset.workspace}
function ensureVirtualDesktops():void{if(!workspaces.list().some((workspace)=>workspace.id==='trading'))workspaces.createWorkspace({id:'trading',name:'Trading',workspace:presetSnapshot('Trading')});if(!workspaces.list().some((workspace)=>workspace.id==='operations'))workspaces.createWorkspace({id:'operations',name:'Operations',workspace:presetSnapshot('Operations')})}
ensureVirtualDesktops()
function detectActiveLayout():string|null{const current=JSON.stringify(captureWorkspace(windows,docks));return layouts.listLayouts().find((layout)=>JSON.stringify(layout.workspace)===current)?.name??null}
const activeLayout=ref<string|null>(restoredPersistedWorkspace?detectActiveLayout():'Default')
const groups=markRaw(createWindowGroupManager(windows))
function defaultGroup():void{try{if(windows.get('colony-main').mode==='normal'&&windows.get('alerts-main').mode==='normal')groups.assign('operations-cluster',['colony-main','alerts-main'])}catch{/* demo windows may not exist in custom layouts */}}
function restoreGroups():void{try{const stored=window.localStorage.getItem(GROUP_STORAGE_KEY);if(stored){groups.restore(JSON.parse(stored) as WindowGroupSnapshot);return}}catch{/* stale group data falls back */}defaultGroup()}
function persistGroups():void{try{window.localStorage.setItem(GROUP_STORAGE_KEY,JSON.stringify(groups.snapshot()))}catch{/* best effort */}}
restoreGroups()
const history=markRaw(createWorkspaceHistory(windows,docks,{limit:50})),historyState=shallowRef(history.state),editState=shallowRef(edit.state)
history.subscribe((state)=>{historyState.value=state});edit.subscribe((state)=>{editState.value=state;persistEdit()});groups.subscribe(persistGroups)
function loadDemoLayout(name:string):void{history.beginTransaction();try{layouts.loadLayout(name);defaultGroup();activeLayout.value=name}finally{history.commitTransaction()}persistWorkspace();persistGroups()}
async function resetWorkspace():Promise<void>{history.beginTransaction();clearWorkspace();edit.restore({mode:'normal',selection:null,paneLocks:[]});try{window.localStorage.removeItem(WORKSPACE_STORAGE_KEY);window.localStorage.removeItem(EDIT_STORAGE_KEY);window.localStorage.removeItem(GROUP_STORAGE_KEY)}catch{/* unavailable */}await nextTick();try{layouts.loadDefaultLayout()}catch{openReferenceLayout()}activeLayout.value='Default';defaultGroup();history.commitTransaction();persistWorkspace();persistEdit();persistGroups()}
function setTheme(theme:DemoThemeName):void{themeName.value=theme;try{window.localStorage.setItem(THEME_STORAGE_KEY,theme)}catch{/* unavailable */}}
function simulateFeedFailure():void{mockProvider.fail(economyKey,new Error('Simulated exchange uplink failure'));feedOnline.value=false}
function recoverFeed():void{mockProvider.recover(economyKey);feedOnline.value=true}
function undo():void{history.undo();activeLayout.value=detectActiveLayout();persistWorkspace()}function redo():void{history.redo();activeLayout.value=detectActiveLayout();persistWorkspace()}
provideDemoControls({theme:()=>themeName.value,setTheme,resetWorkspace,canUndo:()=>historyState.value.canUndo,canRedo:()=>historyState.value.canRedo,undo,redo,workspaceMode:()=>editState.value.mode,setWorkspaceMode:(mode)=>edit.setMode(mode),layoutNames:()=>layouts.listLayouts().map((layout)=>layout.name),activeLayout:()=>activeLayout.value,loadLayout:loadDemoLayout,developerMode:()=>developerMode.value,setDeveloperMode:(enabled)=>{developerMode.value=enabled},feedOnline:()=>feedOnline.value,simulateFeedFailure,recoverFeed})
const workspaceList=shallowRef<readonly WorkspaceRuntime[]>(workspaces.list()),activeWorkspace=shallowRef<WorkspaceRuntime>(workspaces.getActive())
workspaces.subscribe((change)=>{workspaceList.value=change.workspaces;activeWorkspace.value=workspaces.getActive()})
function activateWorkspace(id:string):void{workspaces.activateWorkspace(id)}
persistWorkspace();persistEdit();persistGroups();windows.subscribe(()=>{activeLayout.value=null;persistWorkspace()});docks.subscribe(()=>{activeLayout.value=null;persistWorkspace()})
</script>
<template><ThemeProvider :theme="activeTheme"><DataClientProvider :client="dataClient"><main class="simulation-demo" data-fullscreen-workspace-demo><nav class="workspace-desktops" aria-label="Virtual desktops"><button v-for="workspace in workspaceList" :key="workspace.id" type="button" :data-workspace-tab="workspace.id" :aria-pressed="workspace.id===activeWorkspace.id" @click="activateWorkspace(workspace.id)">{{workspace.name}}</button></nav><div class="workspace-desktop-surface" :data-active-workspace="activeWorkspace.id"><WorkspaceHost :key="activeWorkspace.id" :windows="activeWorkspace.windows" :docks="activeWorkspace.docks" :registry="playgroundWidgetRegistry" :history="activeWorkspace.id==='command'?history:undefined" :edit="activeWorkspace.id==='command'?edit:undefined"/></div><DevToolsOverlay :enabled="developerMode" :windows="activeWorkspace.windows" :docks="activeWorkspace.docks" :data-client="dataClient"/></main></DataClientProvider></ThemeProvider></template>
<style scoped>.simulation-demo{display:flex;width:100%;height:100%;min-width:0;min-height:0;flex-direction:column;background:var(--wf-color-canvas)}.workspace-desktops{display:flex;flex:0 0 32px;align-items:center;gap:2px;padding:0 var(--wf-space-sm);border-bottom:1px solid var(--wf-color-border);background:var(--wf-color-surface-raised)}.workspace-desktops button{height:24px;padding:0 var(--wf-space-md);border:1px solid transparent;border-radius:var(--wf-radius-sm);background:transparent;color:var(--wf-color-text-muted);font:inherit;font-size:var(--wf-font-size-xs);cursor:pointer}.workspace-desktops button:hover{background:var(--wf-color-hover);color:var(--wf-color-text)}.workspace-desktops button[aria-pressed="true"]{border-color:var(--wf-color-focus);background:var(--wf-color-selected);color:var(--wf-color-text)}.workspace-desktops button:focus-visible{outline:2px solid var(--wf-color-focus);outline-offset:1px}.workspace-desktop-surface{position:relative;flex:1 1 auto;min-width:0;min-height:0;overflow:hidden}</style>
