<script setup lang="ts">
import { computed, markRaw, nextTick, ref, shallowRef } from 'vue'
import { DataClientProvider, DevToolsOverlay, ThemeProvider, WorkspaceHost, WorkspaceTabs, captureWorkspace, createActiveWorkspaceNavigator, createDataClient, createDataKey, createLocalStorageWorkspaceCollectionStorage, createLocalStorageWorkspaceLayoutStorage, createMockDataProvider, createSplitPane, createStackPane, createTabPane, createWidgetPane, createWindowGroupManager, createWorkspaceCollection, createWorkspaceEditController, createWorkspaceHistory, createWorkspaceLayoutManager, forgeDarkTheme, forgeLightTheme, provideWidgetNavigation, restoreWorkspace, serializeWorkspace, type WidgetForgeTheme, type WindowGroupSnapshot, type WorkspaceEditSnapshot, type WorkspaceRuntime, type WindowSize } from 'widgetforge'
import { provideDemoControls, type DemoThemeName } from './demo-controls'
import { economyKey, registerEconomyResources } from './economic-domain'
import { playgroundWidgetRegistry } from './playground-widgets'
import { playgroundCommands } from './playground-commands'
import { createReferenceLayout } from './reference-layout'
import AcceptanceWorkspace from './AcceptanceWorkspace.vue'
interface DemoMetric{label:string;value:number;unit:string}
const WORKSPACE_STORAGE_KEY='widgetforge.playground.fullscreen.v3',THEME_STORAGE_KEY='widgetforge.playground.theme',EDIT_STORAGE_KEY='widgetforge.playground.edit.v1',GROUP_STORAGE_KEY='widgetforge.playground.groups.v1',LAYOUT_STORAGE_KEY='widgetforge.playground.layouts.v1',COLLECTION_STORAGE_KEY='widgetforge.playground.workspaces.v1'
function storedTheme():DemoThemeName{try{return window.localStorage.getItem(THEME_STORAGE_KEY)==='forge-light'?'forge-light':'forge-dark'}catch{return'forge-dark'}}
const themeName=ref<DemoThemeName>(storedTheme()),developerMode=ref(false),feedOnline=ref(true),themes:Record<DemoThemeName,WidgetForgeTheme>={'forge-dark':forgeDarkTheme,'forge-light':forgeLightTheme},activeTheme=computed(()=>themes[themeName.value])
const mockProvider=markRaw(createMockDataProvider()),gridPowerKey=createDataKey<DemoMetric>('demo.metric','grid-power'),warehouseKey=createDataKey<DemoMetric>('demo.metric','warehouse-stock')
mockProvider.register({key:gridPowerKey,initial:{label:'Grid Power',value:118.0,unit:'MW'},intervalMs:1_200,update:(current)=>({...current,value:current.value+0.5})});mockProvider.register({key:warehouseKey,initial:{label:'Warehouse Stock',value:640,unit:'t'},intervalMs:1_800,update:(current,tick)=>({...current,value:current.value+(tick%2===0?4:-2)})});registerEconomyResources(mockProvider)
const dataClient=markRaw(createDataClient(mockProvider,{cacheTimeMs:5_000}))
function createDemoWorkspaceCollection(){const create=(persist:boolean)=>createWorkspaceCollection({registry:playgroundWidgetRegistry,...(persist?{storage:createLocalStorageWorkspaceCollectionStorage(window.localStorage,COLLECTION_STORAGE_KEY)}:{})});try{return create(true)}catch{try{window.localStorage.removeItem(COLLECTION_STORAGE_KEY);return create(true)}catch{return create(false)}}}
const workspaces=markRaw(createDemoWorkspaceCollection()),restoredWorkspaceCollection=workspaces.list().length>0
const commandWorkspace=workspaces.list().find((workspace)=>workspace.id==='command')??(restoredWorkspaceCollection?workspaces.getActive():workspaces.createWorkspace({id:'command',name:'Command',activate:true}))
const windows=markRaw(commandWorkspace.windows),docks=markRaw(commandWorkspace.docks),navigator=markRaw(createActiveWorkspaceNavigator(playgroundWidgetRegistry,workspaces)),edit=markRaw(createWorkspaceEditController())
provideWidgetNavigation(navigator)
let workspacePersistQueued=false
function persistWorkspace():void{if(workspacePersistQueued)return;workspacePersistQueued=true;queueMicrotask(()=>{workspacePersistQueued=false;try{window.localStorage.setItem(WORKSPACE_STORAGE_KEY,serializeWorkspace(windows,docks))}catch{/* best effort */}})}
function persistEdit():void{try{window.localStorage.setItem(EDIT_STORAGE_KEY,JSON.stringify(edit.snapshot()))}catch{/* best effort */}}
function restoreEdit():void{try{const stored=window.localStorage.getItem(EDIT_STORAGE_KEY);if(stored)edit.restore(JSON.parse(stored) as WorkspaceEditSnapshot)}catch{/* invalid storage falls back */}}
function referenceWorkspaceSize():WindowSize{return{width:Math.max(1,window.innerWidth),height:Math.max(1,window.innerHeight-32-58-54)}}
function normalizeCurrentWorkspace():void{const container=referenceWorkspaceSize();for(const window of windows.list())windows.constrainToContainer(window.instanceId,container)}
function openReferenceLayout():void{
  const viewport=referenceWorkspaceSize(),layout=createReferenceLayout(viewport)
  docks.add({id:'workspace-top',position:'top',thickness:58,minThickness:50,maxThickness:86,resizable:true,pane:createSplitPane({id:'workspace-top-root',axis:'horizontal',weights:[1,1],settings:{resizable:true,background:'surface'},children:[createWidgetPane({id:'workspace-nav-pane',widgetId:'demo.workspace-topbar',instanceId:'workspace-nav-widget',settings:{sizeMode:'fixed',size:620,minSize:520,maxSize:680,background:'surface'}}),createWidgetPane({id:'workspace-top-metric-pane',widgetId:'demo.live-metric',instanceId:'workspace-top-metric-widget',parameters:{resourceId:'grid-power'},settings:{sizeMode:'flex',minSize:180,background:'surface-raised'}})]})})
  docks.add({id:'workspace-bottom',position:'bottom',thickness:54,minThickness:48,maxThickness:88,resizable:true,pane:createWidgetPane({id:'workspace-command-pane',widgetId:'demo.workspace-commandbar',instanceId:'workspace-command-widget',settings:{background:'surface'}})})
  windows.open({widgetId:'market.ticker',instanceId:'market-main',title:'Helios Commodity Exchange',parameters:{commodity:'METALS',rows:14},position:layout['market-main'].position,size:layout['market-main'].size})
  if (viewport.width < 1200) windows.snapWindow('market-main','left',viewport)
  windows.open({widgetId:'planet.summary',instanceId:'colony-main',title:'ARC-01 Colony Administration',parameters:{planetId:'ARC-01',compact:false},position:layout['colony-main'].position,size:layout['colony-main'].size});windows.open({widgetId:'demo.alerts',instanceId:'alerts-main',position:layout['alerts-main'].position,size:layout['alerts-main'].size});windows.open({widgetId:'demo.live-metric',instanceId:'telemetry-power',title:'Grid Telemetry',parameters:{resourceId:'grid-power'},position:layout['telemetry-power'].position,size:layout['telemetry-power'].size})
  windows.openPane({instanceId:'operations-main',title:'Operations Matrix · responsive locked sidebar',position:layout['operations-main'].position,size:layout['operations-main'].size,minSize:{width:420,height:220},layoutSpec:{horizontal:{start:{target:{kind:'workspace',edge:'left'}},size:{value:28,unit:'percent'}},vertical:{start:{target:{kind:'workspace',edge:'top'}},end:{target:{kind:'workspace',edge:'bottom'}}}},pane:createSplitPane({id:'operations-root',axis:'horizontal',weights:[1,1],children:[createWidgetPane({id:'operations-colony',widgetId:'planet.summary',instanceId:'operations-colony-widget',parameters:{planetId:'ARC-02',compact:true},settings:{sizeMode:'fixed',size:260,minSize:230,maxSize:300,background:'surface'}}),createStackPane({id:'operations-stack',settings:{sizeMode:'flex',background:'surface-raised'},children:[createTabPane({id:'operations-metrics',activeId:'operations-power',children:[createWidgetPane({id:'operations-power',widgetId:'demo.live-metric',instanceId:'operations-power-widget',parameters:{resourceId:'grid-power'},settings:{minSize:90,background:'surface-raised'}}),createWidgetPane({id:'operations-stock',widgetId:'demo.live-metric',instanceId:'operations-stock-widget',parameters:{resourceId:'warehouse-stock'},settings:{minSize:90,background:'canvas'}})]})]})]})});windows.lockWindow('operations-main','api')
  windows.openPane({instanceId:'economy-flow',title:'Colony Economy · Production → Inventory → Orders',position:layout['economy-flow'].position,size:layout['economy-flow'].size,minSize:{width:500,height:280},pane:createSplitPane({id:'economy-flow-root',axis:'horizontal',weights:[1,1],children:[createWidgetPane({id:'economy-production-pane',widgetId:'economy.production',instanceId:'economy-production-widget',settings:{minSize:220,background:'canvas'}}),createTabPane({id:'economy-flow-tabs',activeId:'economy-inventory-pane',children:[createWidgetPane({id:'economy-inventory-pane',widgetId:'economy.inventory',instanceId:'economy-inventory-widget',settings:{minSize:220,background:'canvas'}}),createWidgetPane({id:'economy-orders-pane',widgetId:'economy.orders',instanceId:'economy-orders-widget',settings:{minSize:220,background:'canvas'}})]})]})})
}
function clearWorkspace():void{for(const window of[...windows.list()])windows.close(window.instanceId,'api');for(const dock of[...docks.list()])docks.remove(dock.id)}
let restoredPersistedWorkspace=restoredWorkspaceCollection
function restoreReferenceLayout():void{if(restoredWorkspaceCollection){normalizeCurrentWorkspace();return}let stored:string|null=null;try{stored=window.localStorage.getItem(WORKSPACE_STORAGE_KEY)}catch{/* unavailable */}const restored=stored?restoreWorkspace(windows,stored,docks,undefined,{atomic:true,container:referenceWorkspaceSize()}):null;if(restored?.valid&&restored.issues.length===0&&restored.restoredDocks.length>0){restoredPersistedWorkspace=true;return}clearWorkspace();openReferenceLayout()}
restoreReferenceLayout();restoreEdit()
function createDemoLayoutManager(){const create=(persist:boolean)=>createWorkspaceLayoutManager({registry:playgroundWidgetRegistry,windows,docks,...(persist?{storage:createLocalStorageWorkspaceLayoutStorage(window.localStorage,LAYOUT_STORAGE_KEY)}:{})});try{return create(true)}catch{try{window.localStorage.removeItem(LAYOUT_STORAGE_KEY);return create(true)}catch{return create(false)}}}
const layouts=markRaw(createDemoLayoutManager())
function hasLayout(name:string):boolean{return layouts.listLayouts().some((layout)=>layout.name===name)}
function buildReferencePreset(name:'Default'|'Trading'|'Operations'):void{clearWorkspace();openReferenceLayout();if(name==='Trading'){for(const id of['colony-main','alerts-main','operations-main'])windows.close(id,'api')}else if(name==='Operations')windows.close('market-main','api');layouts.saveLayout(name,{setDefault:name==='Default'})}
function seedDemoLayouts():void{const startup=serializeWorkspace(windows,docks),missing=(['Default','Trading','Operations'] as const).filter((name)=>!hasLayout(name));for(const name of missing)buildReferencePreset(name);if(!layouts.getDefaultLayout()&&hasLayout('Default'))layouts.setDefaultLayout('Default');if(missing.length>0){clearWorkspace();const restored=restoreWorkspace(windows,startup,docks,undefined,{container:referenceWorkspaceSize()});if(!restored.valid||restored.issues.length>0){clearWorkspace();openReferenceLayout();restoredPersistedWorkspace=false}}}
seedDemoLayouts()
function presetSnapshot(name:string){const preset=layouts.listLayouts().find((layout)=>layout.name===name);if(!preset)throw new Error(`missing demo layout ${name}`);return preset.workspace}
function ensureVirtualDesktops():void{if(restoredWorkspaceCollection)return;if(!workspaces.list().some((workspace)=>workspace.id==='trading'))workspaces.createWorkspace({id:'trading',name:'Trading',workspace:presetSnapshot('Trading')});if(!workspaces.list().some((workspace)=>workspace.id==='operations'))workspaces.createWorkspace({id:'operations',name:'Operations',workspace:presetSnapshot('Operations')})}
ensureVirtualDesktops()
function detectActiveLayout():string|null{const current=JSON.stringify(captureWorkspace(windows,docks));return layouts.listLayouts().find((layout)=>JSON.stringify(layout.workspace)===current)?.name??null}
const activeLayout=ref<string|null>(restoredPersistedWorkspace?detectActiveLayout():'Default')
const groups=markRaw(createWindowGroupManager(windows))
function defaultGroup():void{try{if(windows.get('colony-main').mode==='normal'&&windows.get('alerts-main').mode==='normal')groups.assign('operations-cluster',['colony-main','alerts-main'])}catch{/* demo windows may not exist in custom layouts */}}
function restoreGroups():void{try{const stored=window.localStorage.getItem(GROUP_STORAGE_KEY);if(stored){groups.restore(JSON.parse(stored) as WindowGroupSnapshot);return}}catch{/* stale group data falls back */}defaultGroup()}
function persistGroups():void{try{window.localStorage.setItem(GROUP_STORAGE_KEY,JSON.stringify(groups.snapshot()))}catch{/* best effort */}}
restoreGroups()
const history=markRaw(createWorkspaceHistory(windows,docks,{limit:50})),historyState=shallowRef(history.state),editState=shallowRef(edit.state)
history.subscribe((state)=>{historyState.value=state});edit.subscribe((state)=>{editState.value=state;persistEdit()});groups.subscribe(persistGroups)
function openNewWindow():void{if(editState.value.locked)return;const workspace=workspaces.getActive(),workspaceHistory=workspace.id==='command'?history:undefined;workspaceHistory?.beginTransaction();try{workspace.windows.openEmptyWindow({},'user');workspaceHistory?.commitTransaction()}catch{workspaceHistory?.cancelTransaction()}}
function loadDemoLayout(name:string):void{history.beginTransaction();try{layouts.loadLayout(name);normalizeCurrentWorkspace();defaultGroup();activeLayout.value=name}finally{history.commitTransaction()}persistWorkspace();persistGroups()}
async function resetWorkspace():Promise<void>{history.beginTransaction();clearWorkspace();edit.restore({mode:'normal',selection:null,windowSelection:null,paneLocks:[]});try{window.localStorage.removeItem(WORKSPACE_STORAGE_KEY);window.localStorage.removeItem(EDIT_STORAGE_KEY);window.localStorage.removeItem(GROUP_STORAGE_KEY)}catch{/* unavailable */}await nextTick();try{layouts.loadDefaultLayout();normalizeCurrentWorkspace()}catch{openReferenceLayout()}activeLayout.value='Default';defaultGroup();history.commitTransaction();persistWorkspace();persistEdit();persistGroups()}
function setTheme(theme:DemoThemeName):void{themeName.value=theme;try{window.localStorage.setItem(THEME_STORAGE_KEY,theme)}catch{/* unavailable */}}
function simulateFeedFailure():void{mockProvider.fail(economyKey,new Error('Simulated exchange uplink failure'));feedOnline.value=false}
function recoverFeed():void{mockProvider.recover(economyKey);feedOnline.value=true}
function undo():void{history.undo();activeLayout.value=detectActiveLayout();persistWorkspace()}function redo():void{history.redo();activeLayout.value=detectActiveLayout();persistWorkspace()}
provideDemoControls({theme:()=>themeName.value,setTheme,resetWorkspace,canUndo:()=>historyState.value.canUndo,canRedo:()=>historyState.value.canRedo,undo,redo,workspaceMode:()=>editState.value.mode,setWorkspaceMode:(mode)=>edit.setMode(mode),layoutNames:()=>layouts.listLayouts().map((layout)=>layout.name),activeLayout:()=>activeLayout.value,loadLayout:loadDemoLayout,developerMode:()=>developerMode.value,setDeveloperMode:(enabled)=>{developerMode.value=enabled},feedOnline:()=>feedOnline.value,simulateFeedFailure,recoverFeed})
const activeWorkspace=shallowRef<WorkspaceRuntime>(workspaces.getActive())
const acceptanceFixture = typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('fixture') === 'layout-acceptance'
workspaces.subscribe(()=>{activeWorkspace.value=workspaces.getActive()})
persistWorkspace();persistEdit();persistGroups();windows.subscribe((change)=>{activeLayout.value=null;if(!(change.kind==='geometry'&&change.origin==='api'))persistWorkspace()});docks.subscribe(()=>{activeLayout.value=null;persistWorkspace()})
</script>
<template><ThemeProvider :theme="activeTheme"><DataClientProvider :client="dataClient"><AcceptanceWorkspace v-if="acceptanceFixture"/><main v-else class="simulation-demo" data-fullscreen-workspace-demo><WorkspaceTabs :manager="workspaces" :edit="edit"><template #actions><button class="workspace-tabs__new-window" type="button" data-workspace-new-window aria-label="Create new window" title="Create new window" :disabled="editState.locked" @click="openNewWindow"><span aria-hidden="true">+</span><span>New window</span></button></template></WorkspaceTabs><div class="workspace-desktop-surface" :data-active-workspace="activeWorkspace.id"><WorkspaceHost :key="activeWorkspace.id" :windows="activeWorkspace.windows" :docks="activeWorkspace.docks" :registry="playgroundWidgetRegistry" :commands="playgroundCommands" :history="activeWorkspace.id==='command'?history:undefined" :edit="activeWorkspace.id==='command'?edit:undefined"/></div><DevToolsOverlay :enabled="developerMode" :windows="activeWorkspace.windows" :docks="activeWorkspace.docks" :data-client="dataClient"/></main></DataClientProvider></ThemeProvider></template>
<style scoped>.simulation-demo{display:flex;width:100%;height:100%;min-width:0;min-height:0;flex-direction:column;background:var(--wf-color-canvas)}.workspace-desktop-surface{position:relative;flex:1 1 auto;min-width:0;min-height:0;overflow:hidden}.workspace-tabs__new-window{display:inline-flex;min-height:var(--wf-size-control-height);align-items:center;gap:var(--wf-space-xs);padding:0 var(--wf-space-sm);border:1px solid var(--wf-color-border);border-radius:var(--wf-radius-sm);background:var(--wf-color-surface-floating);color:var(--wf-color-text);font:inherit;font-size:var(--wf-font-size-xs);cursor:pointer}.workspace-tabs__new-window:hover:not(:disabled){background:var(--wf-color-hover)}.workspace-tabs__new-window:focus-visible{outline:2px solid var(--wf-color-focus);outline-offset:2px}.workspace-tabs__new-window:disabled{cursor:default;opacity:.6}</style>
