<script setup lang="ts">
import { onBeforeUnmount, onMounted, toRaw } from 'vue'
import type { DockManager, DockRect, DockState } from '../core/dock-manager'
import type { PaneNode } from '../core/pane'
import type { WidgetRegistry } from '../core/widget-registry'
import type { CommandRegistry } from '../core/commands'
import { surfaceStyleToCssVars } from '../core/layout-surface-style'
import PaneHost from './PaneHost.vue'
import { provideWidgetDocumentationForHost } from './documentation-context'
interface Props{dock:DockState;rect:DockRect;manager:DockManager;registry:WidgetRegistry;commands?:CommandRegistry|undefined;layoutLocked?:boolean;editMode?:boolean;layoutSelection?:'selected'|'unselected'|undefined;paneDragEnabled?:(paneId:string)=>boolean}
const props=withDefaults(defineProps<Props>(),{editMode:false,paneDragEnabled:()=>true});const manager=toRaw(props.manager);provideWidgetDocumentationForHost(props.registry, props.commands);let disposeResize:(()=>void)|null=null
function style():Record<string,string>{return{...surfaceStyleToCssVars(props.dock.surfaceStyle),left:`${props.rect.x}px`,top:`${props.rect.y}px`,width:`${props.rect.width}px`,height:`${props.rect.height}px`}}
function updatePane(pane:PaneNode):void{manager.setRootPane(props.dock.id,pane)}function finishResize():void{disposeResize?.()}
function startResize(event:PointerEvent):void{if(props.layoutLocked||!props.dock.resizable||event.button!==0)return;const target=event.currentTarget;if(!(target instanceof HTMLElement))return;event.preventDefault();event.stopPropagation();finishResize();const pointerId=typeof event.pointerId==='number'?event.pointerId:undefined,start=props.dock.position==='top'||props.dock.position==='bottom'?event.clientY:event.clientX,startThickness=props.dock.thickness;if(pointerId!==undefined&&typeof target.setPointerCapture==='function'){try{target.setPointerCapture(pointerId)}catch{/* optional */}}const matches=(next:PointerEvent)=>pointerId===undefined||typeof next.pointerId!=='number'||next.pointerId===pointerId;const move=(next:PointerEvent)=>{if(!matches(next))return;const coordinate=props.dock.position==='top'||props.dock.position==='bottom'?next.clientY:next.clientX,direction=props.dock.position==='bottom'||props.dock.position==='right'?-1:1;manager.setThickness(props.dock.id,startThickness+(coordinate-start)*direction)};const cleanup=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',end);target.removeEventListener('lostpointercapture',lost);if(pointerId!==undefined&&typeof target.releasePointerCapture==='function'){try{target.releasePointerCapture(pointerId)}catch{/* optional */}}if(disposeResize===cleanup)disposeResize=null};const end=(next:PointerEvent)=>{if(matches(next))cleanup()};const lost=()=>cleanup();disposeResize=cleanup;target.addEventListener('lostpointercapture',lost);window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',end)}
function onGlobalKeyDown(event:KeyboardEvent):void{if(event.key==='Escape')finishResize()}
function onGlobalBlur():void{finishResize()}
onMounted(()=>{window.addEventListener('keydown',onGlobalKeyDown);window.addEventListener('blur',onGlobalBlur)})
onBeforeUnmount(()=>{finishResize();window.removeEventListener('keydown',onGlobalKeyDown);window.removeEventListener('blur',onGlobalBlur)})
</script>
<template><section class="wf-dock-host" :class="`wf-dock-host--${dock.position}`" :data-dock-id="dock.id" :data-dock-position="dock.position" :data-layout-selection="layoutSelection" :data-layout-locked="layoutLocked||undefined" :style="style()"><PaneHost :pane="dock.rootPane" :registry="registry" :command-registry="commands" :layout-locked="layoutLocked" :edit-mode="editMode" :pane-drag-enabled="paneDragEnabled" host-type="dock" @update:pane="updatePane"/><div v-if="dock.resizable&&!layoutLocked" class="wf-dock-host__resize" :data-dock-resize="dock.position" aria-hidden="true" @pointerdown="startResize"/></section></template>
<style scoped>.wf-dock-host{position:absolute;min-width:0;min-height:0;overflow:hidden;background:var(--wf-surface-background,var(--wf-color-surface));border:0;border-top:var(--wf-surface-border-top-width,0px) solid var(--wf-surface-border-top-color,var(--wf-color-border));border-right:var(--wf-surface-border-right-width,0px) solid var(--wf-surface-border-right-color,var(--wf-color-border));border-bottom:var(--wf-surface-border-bottom-width,0px) solid var(--wf-surface-border-bottom-color,var(--wf-color-border));border-left:var(--wf-surface-border-left-width,0px) solid var(--wf-surface-border-left-color,var(--wf-color-border));border-radius:var(--wf-surface-radius,0px);box-shadow:var(--wf-surface-shadow,none);opacity:var(--wf-surface-opacity,1);padding:var(--wf-surface-padding-top,0) var(--wf-surface-padding-right,0) var(--wf-surface-padding-bottom,0) var(--wf-surface-padding-left,0);box-sizing:border-box;z-index:calc(var(--wf-layer-window) - 1)}.wf-dock-host__resize{position:absolute;z-index:3;touch-action:none}.wf-dock-host--top .wf-dock-host__resize{right:0;bottom:-3px;left:0;height:6px;cursor:ns-resize}.wf-dock-host--bottom .wf-dock-host__resize{top:-3px;right:0;left:0;height:6px;cursor:ns-resize}.wf-dock-host--left .wf-dock-host__resize{top:0;right:-3px;bottom:0;width:6px;cursor:ew-resize}.wf-dock-host--right .wf-dock-host__resize{top:0;bottom:0;left:-3px;width:6px;cursor:ew-resize}</style>
