<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, shallowRef, toRaw } from 'vue'
import { createContextMenuController, type ContextMenuController, type ContextMenuItem } from '../core/context-menu'
import { calculateWorkspaceDockLayout, type DockManager, type DockState } from '../core/dock-manager'
import { containsPane, findPane, type PaneNode } from '../core/pane'
import type { WidgetRegistry } from '../core/widget-registry'
import type { WindowSize } from '../core/window-geometry'
import type { WindowManager } from '../core/window-manager'
import { createPaneEditContextMenuItems, createWorkspaceEditController, removePaneForEdit, type PaneEditActionId, type WorkspaceEditController, type WorkspaceEditState, type WorkspacePaneOwner, type WorkspacePaneSelection } from '../core/workspace-edit'
import type { WorkspaceHistory } from '../core/workspace-history'
import { detectWorkspaceDropZone, movePaneToTarget, relocatePaneBetweenTrees, type WorkspaceDropRect, type WorkspaceDropZone } from '../core/workspace-docking'
import ContextMenuHost from './ContextMenuHost.vue'
import DockHost from './DockHost.vue'
import DockingOverlay from './DockingOverlay.vue'
import { observeElementSize } from './observe-element-size'
import { handleWorkspaceHistoryShortcut } from './workspace-history-shortcuts'
import WindowManagerHost from './WindowManagerHost.vue'

interface Props { windows:WindowManager;docks:DockManager;registry:WidgetRegistry;history?:WorkspaceHistory|undefined;historyShortcuts?:boolean|undefined;edit?:WorkspaceEditController|undefined;contextMenu?:ContextMenuController|undefined }
interface PaneDragSession { readonly sourceOwner:WorkspacePaneOwner;readonly sourcePaneId:string;readonly sourceElement:HTMLElement;readonly pointerId:number|undefined }
interface PaneDropTarget { readonly owner:WorkspacePaneOwner;readonly paneId:string;readonly zone:WorkspaceDropZone;readonly rect:WorkspaceDropRect }
const props=defineProps<Props>()
const emit=defineEmits<{paneAction:[action:PaneEditActionId,selection:WorkspacePaneSelection]}>()
const windowManager=toRaw(props.windows),dockManager=toRaw(props.docks),registry=toRaw(props.registry),history=props.history?toRaw(props.history):undefined
const editController=props.edit?toRaw(props.edit):createWorkspaceEditController()
const contextMenu=props.contextMenu?toRaw(props.contextMenu):createContextMenuController()
const root=ref<HTMLElement|null>(null),size=shallowRef<WindowSize>({width:0,height:0}),dockStates=shallowRef<readonly DockState[]>(dockManager.list()),editState=shallowRef<WorkspaceEditState>(editController.state),paneDragActive=ref(false),paneDropPreview=shallowRef<PaneDropTarget|null>(null)
let disposeSize:(()=>void)|null=null,disposePaneDrag:(()=>void)|null=null,historyPointerActive=false,dropSequence=0
const unsubscribeDock=dockManager.subscribe((change)=>{dockStates.value=change.docks})
const unsubscribeEdit=editController.subscribe((state)=>{editState.value=state;queueMicrotask(syncEditMarkers)})
const layout=computed(()=>calculateWorkspaceDockLayout(size.value,dockStates.value))
const editMode=computed(()=>editState.value.editActive||paneDragActive.value)
const layoutLocked=computed(()=>editState.value.locked)
function rectStyle(rect:{x:number;y:number;width:number;height:number}):Record<string,string>{return{left:`${rect.x}px`,top:`${rect.y}px`,width:`${rect.width}px`,height:`${rect.height}px`}}
function ownerFromElement(element:Element):WorkspacePaneOwner|null{const w=element.closest<HTMLElement>('[data-window-instance-id]');if(w?.dataset.windowInstanceId)return{kind:'window',id:w.dataset.windowInstanceId};const d=element.closest<HTMLElement>('[data-dock-id]');return d?.dataset.dockId?{kind:'dock',id:d.dataset.dockId}:null}
function ownerRoot(owner:WorkspacePaneOwner):PaneNode{return owner.kind==='window'?windowManager.get(owner.id).rootPane:dockManager.get(owner.id).rootPane}
function setOwnerRoot(owner:WorkspacePaneOwner,pane:PaneNode):void{if(layoutLocked.value)return;if(owner.kind==='window')windowManager.setRootPane(owner.id,pane,'user');else dockManager.setRootPane(owner.id,pane)}
function sameOwner(a:WorkspacePaneOwner,b:WorkspacePaneOwner):boolean{return a.kind===b.kind&&a.id===b.id}
function selectionFor(element:Element,paneId:string):WorkspacePaneSelection|null{const owner=ownerFromElement(element);return owner?{owner,paneId}:null}
function containsPoint(rect:DOMRect,x:number,y:number):boolean{return rect.width>0&&rect.height>0&&x>=rect.left&&x<=rect.right&&y>=rect.top&&y<=rect.bottom}
function syncEditMarkers():void{const workspace=root.value;if(!workspace)return;for(const element of workspace.querySelectorAll<HTMLElement>('.wf-pane-host[data-pane-id]')){element.removeAttribute('data-pane-selected');element.removeAttribute('data-pane-layout-locked');const paneId=element.dataset.paneId;if(!paneId)continue;const selection=selectionFor(element,paneId);if(!selection)continue;if(editState.value.selection&&sameOwner(selection.owner,editState.value.selection.owner)&&selection.paneId===editState.value.selection.paneId)element.dataset.paneSelected='true';if(editController.isPaneLocked(selection))element.dataset.paneLayoutLocked='true'}}
function findDropTarget(session:PaneDragSession,x:number,y:number):PaneDropTarget|null{const workspace=root.value;if(!workspace||layoutLocked.value)return null;const source=findPane(ownerRoot(session.sourceOwner),session.sourcePaneId);if(!source)return null;const candidates=[...workspace.querySelectorAll<HTMLElement>('.wf-pane-host[data-pane-id]')].filter((el)=>!session.sourceElement.contains(el)&&containsPoint(el.getBoundingClientRect(),x,y)).sort((a,b)=>{const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();return ar.width*ar.height-br.width*br.height});for(const candidate of candidates){const cr=candidate.getBoundingClientRect(),zone=detectWorkspaceDropZone({x,y},{x:cr.left,y:cr.top,width:cr.width,height:cr.height});if(!zone)continue;const element=zone==='center'?(candidate.closest<HTMLElement>('.wf-pane-host[data-pane-kind="tabs"]')??candidate):candidate,paneId=element.dataset.paneId,owner=ownerFromElement(element);if(!paneId||!owner)continue;const targetSelection={owner,paneId};if(editController.isPaneLocked(targetSelection))continue;if(sameOwner(owner,session.sourceOwner)&&(paneId===session.sourcePaneId||containsPane(source,paneId)))continue;const r=element.getBoundingClientRect();return{owner,paneId,zone:detectWorkspaceDropZone({x,y},{x:r.left,y:r.top,width:r.width,height:r.height})??zone,rect:{x:r.left,y:r.top,width:r.width,height:r.height}}}return null}
function localTargetRect(target:PaneDropTarget):WorkspaceDropRect{const workspace=root.value;if(!workspace)return target.rect;const r=workspace.getBoundingClientRect();return{x:target.rect.x-r.left,y:target.rect.y-r.top,width:target.rect.width,height:target.rect.height}}
function commitPaneDrop(session:PaneDragSession,target:PaneDropTarget):void{if(layoutLocked.value)return;dropSequence+=1;const id=`workspace-drop-${dropSequence}`;if(sameOwner(session.sourceOwner,target.owner)){setOwnerRoot(session.sourceOwner,movePaneToTarget(ownerRoot(session.sourceOwner),session.sourcePaneId,target.paneId,target.zone,id));return}if(session.sourceOwner.kind==='dock'&&ownerRoot(session.sourceOwner).id===session.sourcePaneId)return;const result=relocatePaneBetweenTrees(ownerRoot(session.sourceOwner),session.sourcePaneId,ownerRoot(target.owner),target.paneId,target.zone,id);setOwnerRoot(target.owner,result.targetRoot);if(result.sourceRoot)setOwnerRoot(session.sourceOwner,result.sourceRoot);else if(session.sourceOwner.kind==='window')windowManager.close(session.sourceOwner.id,'user')}
function finishPaneDrag():void{disposePaneDrag?.()}
function startPaneDrag(event:PointerEvent):void{if(layoutLocked.value||!editState.value.editActive||event.button!==0)return;const target=event.target;if(!(target instanceof HTMLElement)||target.closest('[data-pane-divider-index], [data-window-resize-handle], [data-dock-resize]'))return;const tab=target.closest<HTMLElement>('[data-tab-pane-id]'),pane=target.closest<HTMLElement>('.wf-pane-host[data-pane-id]');if(!pane?.dataset.paneId)return;const owner=ownerFromElement(pane);if(!owner)return;const sourcePaneId=tab?.dataset.tabPaneId??pane.dataset.paneId,sourceRoot=ownerRoot(owner);if(!sourcePaneId||!findPane(sourceRoot,sourcePaneId)||(owner.kind==='dock'&&sourceRoot.id===sourcePaneId))return;const sourceSelection={owner,paneId:sourcePaneId};if(editController.isPaneLocked(sourceSelection))return;event.preventDefault();event.stopPropagation();finishPaneDrag();paneDragActive.value=true;editController.selectPane(sourceSelection);const session:PaneDragSession={sourceOwner:owner,sourcePaneId,sourceElement:tab??pane,pointerId:typeof event.pointerId==='number'?event.pointerId:undefined};const matches=(next:PointerEvent)=>session.pointerId===undefined||typeof next.pointerId!=='number'||next.pointerId===session.pointerId;const move=(next:PointerEvent)=>{if(matches(next))paneDropPreview.value=findDropTarget(session,next.clientX,next.clientY)};const cleanup=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',end);paneDropPreview.value=null;paneDragActive.value=false;if(disposePaneDrag===cleanup)disposePaneDrag=null};const end=(next:PointerEvent)=>{if(!matches(next))return;const drop=paneDropPreview.value;if(next.type==='pointerup'&&drop)commitPaneDrop(session,drop);cleanup()};disposePaneDrag=cleanup;window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',end)}
function selectFromPointer(event:PointerEvent):void{if(!editState.value.editActive||layoutLocked.value)return;const target=event.target;if(!(target instanceof HTMLElement))return;const pane=target.closest<HTMLElement>('.wf-pane-host[data-pane-id]');if(!pane?.dataset.paneId)return;const selection=selectionFor(pane,pane.dataset.paneId);if(selection)editController.selectPane(selection)}
function isLayoutPointer(event:PointerEvent):boolean{if(event.button!==0||!history||layoutLocked.value)return false;const target=event.target;if(!(target instanceof HTMLElement))return false;return Boolean(target.closest('[data-window-drag-handle], [data-window-resize-handle], [data-dock-resize], [data-pane-divider-index]')||(editState.value.editActive&&target.closest('.wf-pane-host[data-pane-id]')))}
function handlePointerDown(event:PointerEvent):void{if(event.ctrlKey&&editState.value.mode==='normal')editController.setTemporaryEdit(true);selectFromPointer(event);if(isLayoutPointer(event)){history?.beginTransaction();historyPointerActive=true}startPaneDrag(event)}
function finishHistoryPointer():void{if(!historyPointerActive)return;historyPointerActive=false;queueMicrotask(()=>history?.commitTransaction())}
function executePaneMenu(item:ContextMenuItem,selection:WorkspacePaneSelection):void{if(layoutLocked.value)return;if(item.id==='lock'){editController.setPaneLocked(selection,true);return}if(item.id==='unlock'){editController.setPaneLocked(selection,false);return}if(item.id==='delete'){const next=removePaneForEdit(ownerRoot(selection.owner),selection.paneId);if(next)setOwnerRoot(selection.owner,next);editController.selectPane(null);return}emit('paneAction',item.id as PaneEditActionId,selection)}
function openPaneMenu(event:MouseEvent):void{if(!editState.value.editActive||layoutLocked.value)return;const target=event.target;if(!(target instanceof HTMLElement))return;const pane=target.closest<HTMLElement>('.wf-pane-host[data-pane-id]');if(!pane?.dataset.paneId)return;const selection=selectionFor(pane,pane.dataset.paneId);if(!selection)return;const paneRoot=ownerRoot(selection.owner),items=createPaneEditContextMenuItems(paneRoot,selection.paneId,editController.isPaneLocked(selection));if(items.length===0)return;event.preventDefault();editController.selectPane(selection);contextMenu.show({x:event.clientX,y:event.clientY,items,onSelect:(item)=>executePaneMenu(item,selection)})}
function onWorkspaceKeyDown(event:KeyboardEvent):void{if(history)handleWorkspaceHistoryShortcut(history,event,props.historyShortcuts!==false)}
function onGlobalKeyDown(event:KeyboardEvent):void{if(event.key==='Escape'){finishPaneDrag();paneDropPreview.value=null;contextMenu.close();return}if(event.key==='Control')editController.setTemporaryEdit(true)}
function onKeyUp(event:KeyboardEvent):void{if(event.key==='Control')editController.setTemporaryEdit(false)}
function onBlur():void{editController.setTemporaryEdit(false);finishPaneDrag();finishHistoryPointer()}
onMounted(()=>{if(root.value){disposeSize=observeElementSize(root.value,(next)=>{size.value=next});root.value.addEventListener('keydown',onWorkspaceKeyDown);queueMicrotask(syncEditMarkers)}window.addEventListener('keydown',onGlobalKeyDown);window.addEventListener('keyup',onKeyUp);window.addEventListener('blur',onBlur);window.addEventListener('pointerup',finishHistoryPointer);window.addEventListener('pointercancel',finishHistoryPointer)})
onBeforeUnmount(()=>{finishPaneDrag();finishHistoryPointer();disposeSize?.();disposeSize=null;unsubscribeDock();unsubscribeEdit();root.value?.removeEventListener('keydown',onWorkspaceKeyDown);window.removeEventListener('keydown',onGlobalKeyDown);window.removeEventListener('keyup',onKeyUp);window.removeEventListener('blur',onBlur);window.removeEventListener('pointerup',finishHistoryPointer);window.removeEventListener('pointercancel',finishHistoryPointer)})
</script>
<template><div ref="root" class="wf-workspace-host" :class="{'wf-workspace-host--edit':editMode,'wf-workspace-host--locked':layoutLocked}" :data-workspace-mode="editState.mode" :data-workspace-edit-mode="editMode" :data-workspace-locked="layoutLocked" @pointerdown.capture="handlePointerDown" @contextmenu.capture="openPaneMenu"><div class="wf-workspace-host__floating" :style="rectStyle(layout.floating)" data-workspace-floating><WindowManagerHost :manager="windowManager" :registry="registry" :layout-locked="layoutLocked"/></div><DockHost v-for="dock in dockStates" :key="dock.id" :dock="dock" :rect="layout.docks[dock.id]??{x:0,y:0,width:0,height:0}" :manager="dockManager" :registry="registry" :layout-locked="layoutLocked"/><DockingOverlay v-if="paneDropPreview&&!layoutLocked" :target-rect="localTargetRect(paneDropPreview)" :active-zone="paneDropPreview.zone" :source-id="paneDropPreview.owner.id" :target-id="paneDropPreview.paneId"/><ContextMenuHost :controller="contextMenu"/></div></template>
<style scoped>.wf-workspace-host{position:relative;width:100%;height:100%;min-width:0;min-height:0;overflow:hidden;background:var(--wf-color-canvas)}.wf-workspace-host__floating{position:absolute;min-width:0;min-height:0;overflow:hidden}.wf-workspace-host--edit :deep(.wf-pane-host){position:relative;outline:1px dashed var(--wf-color-border);outline-offset:-1px}.wf-workspace-host--edit :deep(.wf-pane-host:hover){outline-color:var(--wf-color-focus)}.wf-workspace-host--edit :deep(.wf-pane-host[data-pane-selected="true"]){outline:2px solid var(--wf-color-focus);outline-offset:-2px}.wf-workspace-host--edit :deep(.wf-pane-host[data-pane-selected="true"]::before){content:attr(data-pane-id);position:absolute;top:2px;left:2px;z-index:var(--wf-layer-overlay);padding:1px var(--wf-space-xs);border-radius:var(--wf-radius-sm);background:var(--wf-color-surface-raised);color:var(--wf-color-text-muted);font-size:var(--wf-font-size-xs);pointer-events:none}.wf-workspace-host--edit :deep(.wf-pane-host[data-pane-layout-locked="true"]){outline-style:solid;outline-color:var(--wf-color-warning)}.wf-workspace-host--edit :deep([data-pane-divider-index]),.wf-workspace-host--edit :deep([data-window-resize-handle]),.wf-workspace-host--edit :deep([data-dock-resize]){background:var(--wf-color-hover)}.wf-workspace-host--locked{cursor:default}</style>
