export { default as ThemeProvider } from './vue/ThemeProvider.vue'
export { createTheme, defaultTheme, themeToCssVariables } from './vue/theme'
export type { DeepPartial, WidgetForgeTheme, WidgetForgeThemeOverride } from './vue/theme'
export { useTheme } from './vue/theme-context'
export { default as WidgetHost } from './vue/WidgetHost.vue'
export { default as WidgetViewStateProvider } from './vue/WidgetViewStateProvider.vue'
export { provideWidgetViewState, useWidgetViewState, WidgetViewStateUnavailableError } from './vue/widget-view-state'
export type { WidgetViewStateContext, WidgetViewStateHostContext } from './vue/widget-view-state'
export { createLocalStorageWidgetViewStateStorage, DEFAULT_WIDGET_VIEW_STATE_STORAGE_KEY } from './vue/widget-view-state-storage'
export { default as SelectionProvider } from './vue/SelectionProvider.vue'
export { provideSelectionStore, useSelection, useSelectionStore, SelectionUnavailableError } from './vue/selection-context'
export type { SelectionBinding } from './vue/selection-context'
export { useLinkedSelection } from './vue/linked-selection'
export type { LinkedSelectionAdapter, LinkedSelectionBinding, LinkedSelectionViewState } from './vue/linked-selection'
export { default as WidgetActionToolbar } from './vue/WidgetActionToolbar.vue'
export { provideWidgetActionExecutor, useWidgetActionExecutor } from './vue/widget-action-execution'
export { default as PaneHost } from './vue/PaneHost.vue'
export { PaneContextUnavailableError, usePaneContext } from './vue/pane-context'
export type { PaneContext, PaneHostType } from './vue/pane-context'
export { createLocalStorageWorkspaceLayoutStorage, DEFAULT_WORKSPACE_LAYOUT_STORAGE_KEY } from './vue/workspace-layout-storage'
export { createLocalStorageWorkspaceCollectionStorage, DEFAULT_WORKSPACE_COLLECTION_STORAGE_KEY } from './vue/workspace-collection-storage'
export { default as DockHost } from './vue/DockHost.vue'
export { default as WorkspaceHost } from './vue/WorkspaceHost.vue'
export { default as WorkspaceCollectionHost } from './vue/WorkspaceCollectionHost.vue'
export { default as WorkspaceTabs } from './vue/WorkspaceTabs.vue'
export { default as DockingOverlay } from './vue/DockingOverlay.vue'
export { default as WindowSnapLayoutPicker } from './vue/WindowSnapLayoutPicker.vue'
export { default as DevToolsOverlay } from './vue/DevToolsOverlay.vue'
export { useWidgetContext } from './vue/widget-context'
export type { WidgetActionContext, WidgetContext } from './vue/widget-context'
export { provideWidgetNavigation, useWidgetNavigation, WidgetNavigationUnavailableError } from './vue/widget-navigation'
export { default as CommandInput } from './vue/CommandInput.vue'
export { default as CommandLauncher } from './vue/CommandLauncher.vue'
export { default as HelpWidget } from './vue/HelpWidget.vue'
export { default as CommandPalette } from './vue/CommandPalette.vue'
export { default as DataClientProvider } from './vue/DataClientProvider.vue'
export { DataClientUnavailableError, provideDataClient, useData, useDataClient } from './vue/data-context'
export { default as MutationClientProvider } from './vue/MutationClientProvider.vue'
export { MutationClientUnavailableError, provideMutationClient, useMutation, useMutationClient } from './vue/mutation-context'
export type { MutationBinding } from './vue/mutation-context'
export { default as WindowShell } from './vue/WindowShell.vue'
export { default as WindowManagerHost } from './vue/WindowManagerHost.vue'
export { default as NotificationToastHost } from './vue/NotificationToastHost.vue'
export { default as NotificationCenter } from './vue/NotificationCenter.vue'
export { default as ContextMenuHost } from './vue/ContextMenuHost.vue'
export { default as ConfirmationDialog } from './vue/ConfirmationDialog.vue'
export { default as WindowLayoutDialog } from './vue/WindowLayoutDialog.vue'
export { forgeDarkTheme, forgeLightTheme } from './presets/forge'
export { default as InfoPopover } from './primitives/InfoPopover.vue'
export type { InfoPopoverPlacement } from './primitives/InfoPopover.vue'
export { default as KeyValueGroup } from './primitives/KeyValueGroup.vue'
export { default as KeyValueRow } from './primitives/KeyValueRow.vue'
export { default as StatValue } from './primitives/StatValue.vue'
export { default as SimpleTable } from './primitives/SimpleTable.vue'
export type { SimpleTableAlign, SimpleTableColumn } from './primitives/simple-table'
export { default as DataTable } from './primitives/DataTable.vue'
export { filterDataTableRows, nextDataTableSort, processDataTableRows, sortDataTableRows, visibleDataTableColumns } from './primitives/data-table'
export type { DataTableColumn, DataTableRowId, DataTableSort, DataTableSortDirection } from './primitives/data-table'
export { default as LoadingState } from './primitives/LoadingState.vue'
export { default as EmptyState } from './primitives/EmptyState.vue'
export { default as ErrorState } from './primitives/ErrorState.vue'
export { createDataClient, createDataKey, dataKeyId, DataClient, InvalidDataKeyError } from './data/data-client'
export type { DataClientDiagnostics, DataClientDiagnosticsListener, DataClientOptions, DataClientResourceDiagnostic, DataHandle, DataKey, DataObserver, DataProvider, DataState, DataStateRef, DataUnsubscribe } from './data/data-client'
export { createMutationClient, createMutationDefinition, InvalidMutationDefinitionError, MutationClient, MutationError, mutationDefinitionId, normalizeMutationError } from './data/mutation-client'
export type { MutationClientDiagnostics, MutationClientDiagnosticsListener, MutationDefinition, MutationErrorKind, MutationErrorOptions, MutationHandle, MutationHandleDiagnostic, MutationInvocationContext, MutationProvider, MutationState, MutationStateRef, MutationUnsubscribe } from './data/mutation-client'
export { createMockDataProvider, DuplicateMockDataResourceError, MockDataProvider, UnknownMockDataResourceError } from './data/mock-data-provider'
export type { MockDataResourceDefinition } from './data/mock-data-provider'
export { createRealtimeDataProvider, createRealtimeMutationProvider, RealtimeDataProvider, RealtimeMutationProvider } from './data/realtime-transport'
export type { RealtimeConnectionListener, RealtimeConnectionState, RealtimeConnectionStateRef, RealtimeConnectionStatus, RealtimeConnectionTransport, RealtimeMutationTransport, RealtimeResourceObserver, RealtimeTransport } from './data/realtime-transport'
export { createSelectionKey, createSelectionStore, selectionKeyId, SelectionDefinitionError, SelectionStore } from './core/selection'
export type { SelectionChange, SelectionKey, SelectionListener } from './core/selection'
export { defineWidget, resolveWidgetCapabilities, WidgetDefinitionError } from './core/widget'
export type { InferWidgetParameters, ResolvedWidgetCapabilities, WidgetCapabilities, WidgetId, WidgetManifest, WidgetParameterDefinition, WidgetParameterSchema, WidgetSize, WidgetWindowMetadata } from './core/widget'
export { createCommandDocumentationView, createWidgetDocumentationView } from './core/documentation'
export type { CommandArgumentDocumentation, CommandDocumentationView, DocumentationMetadata, DocumentationScalar, WidgetDocumentationView, WidgetParameterDocumentation } from './core/documentation'
export { createHelpDocumentationSnapshot, searchHelpDocumentation } from './core/help-documentation'
export type { HelpCommandReference, HelpDocumentationSnapshot, HelpReferenceEntry, HelpReferenceFilter, HelpSearchResult, HelpWidgetReference } from './core/help-documentation'
export { HELP_WIDGET_ID } from './core/help-widget'
export { assertPaneCapabilities, paneIsDockable, paneIsTabCompatible, WidgetCapabilityError } from './core/widget-capabilities'
export type { PaneCapabilityPolicy, WidgetCapabilityName } from './core/widget-capabilities'
export { createWidgetViewStateStore, isWidgetViewStateValue, validateWidgetViewStateDefinition, WidgetViewStateError, WidgetViewStateStore } from './core/widget-view-state'
export type { WidgetViewStateDefinition, WidgetViewStateHandle, WidgetViewStatePrimitive, WidgetViewStateSnapshot, WidgetViewStateSnapshotEntry, WidgetViewStateStorage, WidgetViewStateValue } from './core/widget-view-state'
export { cloneWidgetAction, validateWidgetAction, validateWidgetActions, WidgetActionDefinitionError, WidgetActionExecutionError } from './core/widget-actions'
export type { WidgetAction, WidgetActionTone, WidgetActionTarget, WidgetActionStatePatch, WidgetActionExecutionContext, WidgetActionHandler, WidgetActionBinding, WidgetActionExecutor } from './core/widget-actions'
export { calculateWidgetActionOverflow } from './core/widget-action-overflow'
export type { WidgetActionOverflowLayout, WidgetActionOverflowOptions } from './core/widget-action-overflow'
export { COMMAND_LAUNCHER_WIDGET_ID, createCommandLauncherPane, createWidgetPane, createSplitPane, createTabPane, createStackPane, clonePaneTree, validatePaneTree, findPane, containsPane, replacePane, removePane, splitPaneAt, tabPaneAt, movePane, movePaneToTabs, setSplitWeights, setActiveTab, reorderTab, setPaneCollapsed, isCommandLauncherPane, PaneDefinitionError, UnknownPaneError, InvalidPaneOperationError } from './core/pane'
export type { PaneId, PaneAxis, PaneOverflow, PaneBackground, PaneParameterValue, PaneParameters, PaneSplitEdge, PaneSizeMode, PaneSettings, WidgetPane, CommandLauncherPane, SplitPane, TabPane, StackPane, PaneNode, CreateWidgetPaneOptions, CreateCommandLauncherPaneOptions, CreateSplitPaneOptions, CreateTabPaneOptions, CreateStackPaneOptions, RemovePaneResult } from './core/pane'
export { calculatePaneSplitLayout, resizePaneSplitWeights } from './core/pane-layout'
export type { PaneIntrinsicSizes, PaneSplitLayout, PaneSplitLayoutItem } from './core/pane-layout'
export { createDockManager, calculateWorkspaceDockLayout, DockManager, DuplicateDockError, UnknownDockError, DockDefinitionError } from './core/dock-manager'
export type { DockId, DockPosition, DockChangeKind, DockState, DockRestoreWindow, AddDockRequest, DockChange, DockRect, WorkspaceDockLayout, DockListener } from './core/dock-manager'
export { captureWidgetForgeDevToolsSnapshot } from './core/devtools'
export type { DevToolsDockDiagnostic, DevToolsPaneDiagnostic, DevToolsPaneOwnerKind, DevToolsWindowDiagnostic, WidgetForgeDevToolsSnapshot } from './core/devtools'
export { createWidgetLifecycle, InvalidWidgetLifecycleTransitionError, WidgetLifecycleController } from './core/widget-lifecycle'
export type { WidgetLifecycle, WidgetLifecycleEvent, WidgetLifecycleEventKind, WidgetLifecycleListener, WidgetLifecycleState } from './core/widget-lifecycle'
export { createWidgetRegistry, DuplicateWidgetIdError, UnknownWidgetError, validateWidgetParameters, WidgetParameterValidationError, WidgetRegistry } from './core/widget-registry'
export type { ResolvedWidget, WidgetParameterIssue, WidgetParameterIssueCode, WidgetParameterValidationResult } from './core/widget-registry'
export { createActiveWorkspaceNavigator, createWidgetNavigator, ActiveWorkspaceNavigatorService, WidgetNavigationError, WidgetNavigatorService } from './core/navigation'
export type { ActiveWorkspaceNavigationSource, NavigationIntent, NavigationResult, WidgetNavigationContext, WidgetNavigationErrorCode, WidgetNavigator } from './core/navigation'
export { createWidgetDocumentationProvider, provideWidgetDocumentation, useOptionalWidgetDocumentation, useWidgetDocumentation, WidgetDocumentationUnavailableError } from './vue/documentation-context'
export type { WidgetDocumentationProvider } from './vue/documentation-context'
export { createNotificationStore, NotificationDefinitionError, NotificationStore } from './core/notifications'
export type { NotificationId, NotificationInput, NotificationItem, NotificationSeverity, NotificationStoreListener, NotificationStoreOptions, NotificationStoreUnsubscribe } from './core/notifications'
export { ContextMenuController, ContextMenuDefinitionError, createContextMenuController } from './core/context-menu'
export type { ContextMenuItem, ContextMenuItemTone, ContextMenuListener, ContextMenuRequest, ContextMenuState, ContextMenuUnsubscribe } from './core/context-menu'
export { CommandDefinitionError, CommandParseError, CommandRegistry, createCommandRegistry } from './core/commands'
export type { CommandArgumentDefinition, CommandArgumentType, CommandDefinition, CommandParseErrorCode } from './core/commands'
export { CommandPaletteDefinitionError, CommandPaletteRegistry, createCommandPaletteProvider, createCommandPaletteRegistry, createCommandRegistryPaletteProvider, createWidgetActionPaletteProvider, createWidgetRegistryPaletteProvider, rankCommandPaletteItems } from './core/command-palette'
export type { CommandPaletteItem, CommandPaletteProvider, CommandPaletteSearchResult, WidgetActionPaletteProviderOptions } from './core/command-palette'
export { captureWorkspace, commitWorkspacePaneMutations, restoreWorkspace, serializeWorkspace, validateWorkspaceSnapshot, WORKSPACE_VERSION, WorkspaceInvariantError, WorkspaceMutationError, WorkspaceSerializationError } from './core/workspace'
export type { WorkspaceMutationOwner, WorkspaceParameters, WorkspaceParameterValue, WorkspacePaneMutation, WorkspaceRestoreIssue, WorkspaceRestoreIssueCode, WorkspaceRestoreOptions, WorkspaceRestoreResult, WorkspaceSnapshot, WorkspaceWindowSnapshot, WorkspaceDockSnapshot } from './core/workspace'
export { createWorkspaceMigrationRegistry, createDefaultWorkspaceMigrationRegistry, defaultWorkspaceMigrationRegistry, migrateWorkspaceV1ToV2, migrateWorkspaceV2ToV3, WorkspaceMigrationRegistry, WorkspaceMigrationError } from './core/workspace-migrations'
export type { WorkspaceMigrationDocument, WorkspaceMigrationStep, WorkspaceMigrationDefinition, WorkspaceMigrationResult, WorkspaceMigrationErrorCode } from './core/workspace-migrations'
export { createWorkspaceLayoutManager, WorkspaceLayoutManager, WorkspaceLayoutError, WORKSPACE_LAYOUT_PRESET_VERSION, WORKSPACE_LAYOUT_COLLECTION_VERSION } from './core/workspace-layouts'
export type { WorkspaceLayoutErrorCode, WorkspaceLayoutPreset, WorkspaceLayoutCollectionSnapshot, WorkspaceLayoutStorage, WorkspaceLayoutManagerOptions, SaveWorkspaceLayoutOptions, WorkspaceLayoutLoadResult } from './core/workspace-layouts'
export { createWorkspaceCollection, WorkspaceCollectionManager, WorkspaceCollectionError, WORKSPACE_COLLECTION_VERSION } from './core/workspace-collection'
export type { WorkspaceId, WorkspaceRuntime, WorkspaceCollectionEntrySnapshot, WorkspaceCollectionSnapshot, WorkspaceCollectionStorage, WorkspaceCollectionOptions, CreateWorkspaceRequest, DuplicateWorkspaceRequest, WorkspaceCollectionChangeKind, WorkspaceCollectionChange, WorkspaceCollectionListener, WorkspaceCollectionErrorCode } from './core/workspace-collection'
export { createWorkspaceHistory, WorkspaceHistory, WorkspaceHistoryError } from './core/workspace-history'
export type { WorkspaceHistoryOptions, WorkspaceHistoryState, WorkspaceHistoryListener } from './core/workspace-history'
export { createWorkspaceEditController, WorkspaceEditController, createPaneEditContextMenuItems, removePaneForEdit, retargetWidgetPane } from './core/workspace-edit'
export type { WorkspaceEditMode, WorkspacePaneOwnerKind, WorkspacePaneOwner, WorkspacePaneSelection, WorkspaceWindowSelection, WorkspaceEditSnapshot, WorkspaceEditState, WorkspaceEditListener, PaneEditActionId } from './core/workspace-edit'
export { DEFAULT_LAUNCHER_WINDOW_SIZE, DEFAULT_LAUNCHER_WINDOW_TITLE, createWindowManager, DuplicateWindowInstanceError, UnknownWindowInstanceError, WindowLayoutLockedError, WindowManager } from './core/window-manager'
export type { OpenLauncherWindowRequest, OpenPaneWindowRequest, OpenWindowRequest, ReplaceLauncherWindowRequest, WindowInstanceId, WindowManagerChange, WindowManagerChangeKind, WindowManagerListener, WindowMode, WindowOperationOrigin, WindowState } from './core/window-manager'
export { createWindowGroupManager, getWindowGroupManager, WindowGroupDefinitionError, WindowGroupManager } from './core/window-groups'
export type { WindowGroupId, WindowGroupState, WindowGroupSnapshot, WindowGroupMoveSnapshot, WindowGroupChange, WindowGroupListener } from './core/window-groups'
export { createWindowOptions, defaultWindowOptions, windowRoleRank, WindowOptionsError } from './core/window-options'
export type { WindowChromeMode, WindowHeaderAction, WindowHeaderActionInput, WindowHeaderActionSide, WindowHeaderMode, WindowLayer, WindowRole, WindowOptions, WindowOptionsOverride } from './core/window-options'
export { DEFAULT_MIN_VISIBLE, DEFAULT_MIN_WINDOW_SIZE, DEFAULT_WINDOW_SIZE, constrainGeometry, constrainPosition, constrainSize, moveWindow, moveWindowGroup, normalizeWindowGeometry, resizeWindow, sameGeometry } from './core/window-geometry'
export type { ResizeHandle, WindowGeometry, WindowGroupGeometry, WindowPosition, WindowSize, WindowSizeConstraints } from './core/window-geometry'
export { cloneWindowLayoutSpec, convertWindowLayoutValue, createAbsoluteWindowLayoutSpec, createWindowLayoutConstraintDraft, createWindowLayoutSpecFromSnap, deriveWindowLayoutAxisMode, deriveWindowLayoutStatus, findWindowLayoutDependents, layoutSpecReferencesWindow, removeWindowLayoutConstraint, resolveWindowLayoutSpecs, setWindowLayoutConstraint, validateWindowLayoutReferences, validateWindowLayoutSpec, WindowLayoutValidationError } from './core/window-layout'
export type { ResponsiveLayoutWindow, WindowLayoutAnchor, WindowLayoutAxisMode, WindowLayoutAxisSpec, WindowLayoutEdge, WindowLayoutLength, WindowLayoutRuleState, WindowLayoutSize, WindowLayoutSpec, WindowLayoutStatus, WindowLayoutStatusInput, WindowLayoutSurfaceState, WindowLayoutTarget, WindowLayoutUnit, WindowLayoutValidationErrorCode, WindowLayoutWindowTarget, WindowLayoutWorkspaceTarget } from './core/window-layout'
export { DEFAULT_SNAP_THRESHOLD, WINDOW_SNAP_LAYOUTS, WINDOW_SNAP_ZONES, detectWindowSnapZone, isWindowSnapZone, maximizeWindowGeometry, restoreFloatingWindowGeometry, snapWindowGeometry, windowSnapZoneLabel } from './core/window-snap'
export type { WindowSnapLayoutDefinition, WindowSnapPreview, WindowSnapState, WindowSnapZone } from './core/window-snap'
export { detectWorkspaceDropZone, workspaceDropPreviewRect, dropPaneAt, movePaneToTarget, relocatePaneBetweenTrees, dockWindowIntoWindow, anchorWindowToDock, detachDockToWindow, WorkspaceDockTransformError } from './core/workspace-docking'
export type { WorkspaceDropZone, WorkspaceDropRect, WorkspacePoint, RelocatePaneResult, AnchorWindowToDockRequest, DetachDockToWindowRequest } from './core/workspace-docking'
