<script setup lang="ts">
import { computed } from 'vue'
import { DataTable, EmptyState, ErrorState, LoadingState, useData, useLinkedSelection, useWidgetViewState, type DataTableColumn, type DataTableSort } from 'widgetforge'
import { economyKey, type InventoryItem } from '../economic-domain'
import { colonySelectionKey } from '../selection-demo'
type ViewState={filter:string;sortColumn:string;sortDirection:'asc'|'desc';selection:{followSelection:boolean;pinnedSelection:string|null}}
const viewState=useWidgetViewState<ViewState>(),state=useData(economyKey),linked=useLinkedSelection<string,ViewState>(colonySelectionKey,{read:(value)=>value.selection,write:(value,selection)=>({...value,selection})})
const location=computed(()=>state.value.status==='ready'&&linked.selection.value?state.value.data.locations[linked.selection.value as keyof typeof state.value.data.locations]:null)
const filter=computed({get:()=>viewState.state.value.filter,set:(filter:string)=>viewState.update((current)=>({...current,filter}))})
const rows=computed(()=>{const query=filter.value.trim().toLowerCase();return (location.value?.inventory??[]).filter((item)=>!query||item.name.toLowerCase().includes(query))})
const sort=computed<DataTableSort>({get:()=>({columnId:viewState.state.value.sortColumn,direction:viewState.state.value.sortDirection}),set:(next)=>viewState.update((current)=>({...current,sortColumn:next.columnId,sortDirection:next.direction}))})
const columns:readonly DataTableColumn<InventoryItem>[]=[{id:'name',header:'Material',value:(row)=>row.name},{id:'quantity',header:'Stock',align:'end',value:(row)=>row.quantity,format:(value)=>Number(value).toLocaleString('en-US')},{id:'capacity',header:'Capacity',align:'end',value:(row)=>row.capacity,format:(value)=>Number(value).toLocaleString('en-US')},{id:'fill',header:'Fill',align:'end',value:(row)=>row.quantity/row.capacity,format:(value)=>`${Math.round(Number(value)*100)}%`}]
</script>
<template><article class="inventory-widget" :data-selection="linked.selection.value??undefined" :data-following="String(linked.following.value)"><header><div><span>Inventory control</span><strong>{{location?.name??'No location'}}</strong></div><label>Filter <input v-model="filter" aria-label="Inventory filter" type="search"/></label></header><LoadingState v-if="state.status==='loading'" label="Loading inventory"/><ErrorState v-else-if="state.status==='error'" title="Inventory feed unavailable" :message="state.error.message"/><EmptyState v-else-if="rows.length===0" title="No matching inventory"/><DataTable v-else v-model:sort="sort" :rows="rows" :columns="columns" :row-id="(row:InventoryItem)=>row.id" aria-label="Inventory stock" compact/></article></template>
<style scoped>.inventory-widget{height:100%;display:grid;grid-template-rows:auto minmax(0,1fr);gap:var(--wf-space-sm);padding:var(--wf-space-md);overflow:hidden;background:var(--wf-color-canvas)}header{display:flex;align-items:center;justify-content:space-between;gap:var(--wf-space-md)}header>div{display:grid;gap:2px}header span,label{color:var(--wf-color-text-muted);font-size:var(--wf-font-size-xs);text-transform:uppercase;letter-spacing:.07em}label{display:flex;align-items:center;gap:var(--wf-space-xs)}input{width:110px;height:26px;border:1px solid var(--wf-color-border);border-radius:var(--wf-radius-sm);background:var(--wf-color-surface);color:var(--wf-color-text)}</style>
